### ISSUE TITLE
Docker Image Run with Docker Compose

### ISSUE THREAD

**Issue by st120712** [nhnacademy-aiot2-lucky7/common-infra#13]
# 🐳 Docker Compose 기반 서비스 실행 및 설정 구조 안내

GHCR(GitHub Container Registry)에 푸시된 이미지를 기반으로 Docker Compose로 각 서비스를 실행하기 위한 구조 및 설정 방식입니다.  
모든 서비스는 환경 변수 파일(`.env`)을 통해 민감 정보를 주입받으며, 로그와 네트워크 설정은 Compose에서 통합 관리됩니다.

---

## 🔁 GitHub Actions - Reusable Docker Publish Workflow

해당 워크플로는 각 서비스에서 GitHub Actions로 이미지를 빌드하고 GHCR에 푸시할 수 있도록 재사용 가능한 구조로 작성되었습니다.

```yaml
name: Reusable Docker Publish Workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        type: string
        default: Dockerfile
      use-github-token:
        required: false
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')

          if [ "${{ inputs.use-github-token }}" = "true" ]; then
            docker build \
              --build-arg GITHUB_ACTOR=${{ github.actor }} \
              --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
              -t $IMAGE_ID -f ${{ inputs.dockerfile-path }} .
          else
            docker build \
              -t $IMAGE_ID -f ${{ inputs.dockerfile-path }} .
          fi

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}:latest
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_ID
```

---

## ⚙️ 환경 변수 파일 (`.env.example`)

서비스별 `.env` 파일은 민감한 설정값들을 외부에서 주입하기 위해 사용됩니다.  
실제 `.env.auth`, `.env.user` 등으로 복사해서 사용하며, Git에는 절대 커밋하지 않습니다.

```env
SERVER_IP_ADDRESS=

# AES 암호화 키
AES_SECRET=

# Redis 설정
REDIS_HOST=
REDIS_PORT=
REDIS_PASSWORD=

# JWT 설정
JWT_SECRET=

# Spring Profile
SPRING_PROFILES_ACTIVE=release
#EUREKA_URL=https://admin:1234@eureka.luckyseven.live/eureka
```

> ⚠️ `.env.example` 파일은 참고용이며, 실제 실행을 위해 각 서비스별 `.env.<서비스명>` 파일을 생성해야 합니다.

---

## 🧩 Docker Compose 설정 (`docker-compose.yml`)

서비스를 실행하는 실제 Compose 파일 예시는 다음과 같습니다:

```yaml
services:
  auth-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/auth-service:latest
    container_name: team1-auth-service
    ports:
      - "10234:10234"
    env_file:
      - .env.auth
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true
```

### 주요 항목 설명

| 항목 | 설명 |
|------|------|
| `image` | GHCR에서 가져온 최신 버전의 이미지 지정 |
| `container_name` | 실제 생성될 컨테이너 이름 |
| `ports` | 호스트 ↔ 컨테이너 포트 바인딩 |
| `env_file` | 환경 변수 주입을 위한 `.env.auth` 지정 |
| `volumes` | 로그 디렉토리 등 호스트와 컨테이너 간 공유 디렉토리 설정 |
| `networks` | 외부 네트워크 `team1-net`에 연결하여 다른 서비스와 통신 가능하게 함 |

---

## ✅ 운영 규칙 정리

- **이미지는 GHCR에 등록된 최신 `:latest` 태그로 관리**  
- **환경 변수는 `.env.<서비스명>` 파일을 통해 외부 주입 (Git에 커밋 ❌)**  
- **로그는 `./logs` 디렉토리에 저장되며, Compose에서 마운트 처리**  
- **네트워크는 `team1-net`로 통합하여 서비스 간 통신 지원**

---

## 📌 팀 TODO

- [ ] `.env.example` 파일을 참고해 `.env.<서비스명>` 생성
- [ ] 각 환경 변수 입력 (`AES_SECRET`, `JWT_SECRET`, `REDIS_*` 등)
- [ ] `docker-compose up -d`로 실행하여 로그/포트 정상 여부 확인
- [ ] 필요 시 추가 네트워크/볼륨 구성 논의

---

## 📁 .gitignore 예시

```gitignore
# 환경 변수 파일은 Git에 포함 금지
.env*
!*.example

# 로그 및 빌드 산출물
logs/
build/
target/
```

---

> ❗ 이슈에 추가할 서비스가 있거나 네트워크 구조 변경 사항이 있다면 댓글로 알려주세요.
